TECH-5748/merge rename service classes
Invoca/git_lib pull request #59
Opened 2021-08-23 23:02 UTC by ColinDKelley

Minor change in support of TECH-5748. I did a major version bump since the new keyword argument is required.

## [2.0.0] - Unreleased
### Changed
- Add required `repository:` to `GitCommit`.

2021-08-23 23:38 UTC, yinonrousso requested changes
Looks good 💯 . Just one minor suggestion mentioned below

2021-08-23 23:38 UTC, yinonrousso commented on spec/spec_helper.rb
> +
Looks like this rspec config is a duplicate of line 32 above
```suggestion
```

2021-08-23 23:50 UTC, yinonrousso approved these changes

2021-08-24 00:06 UTC, ColinDKelley commented
Thanks for catching that, @yinonrousso. As you could probably tell, I copied those settings over from `deploybot`.

2021-08-24 16:15 UTC, merged